### ISSUE TITLE
Hello, I encountered this problem when I reapped your code. How to solve it?

### ISSUE THREAD

**Issue by xin4431** [vanhaito/YOLOX-ByteTrack-Car-Counter#1]
![无标1](https://user-images.githubusercontent.com/99191183/165317777-7b9f7055-cede-4c3d-841b-77a15659c5a2.png)
)
Hello, I encountered this problem when I reapped your code. How to solve it?

**Comment by vanhaito** [comment]
@xin4431 https://github.com/NVIDIA-AI-IOT/torch2trt clone and install to convert model into tensorrt.

**Comment by xin4431** [comment]
![无标题1](https://user-images.githubusercontent.com/99191183/165693767-32d9784f-f6e1-4863-bebd-93eb54c90c05.png)
Sorry to bother you again.
The previous problem has been solved, but a new one has appeared, as shown in the figure:
I get an error when pycharm runs trt.py. Then run python tools/trt.py -n yolox-s -c yolox_s.pth with cmd to prompt an error.
Where is my problem please?
Thanks!

**Comment by vanhaito** [comment]
Did you install YOLOX @xin4431 ?

**Comment by xin4431** [comment]
I completed it through trt.py and the model was replaced.

![1](https://user-images.githubusercontent.com/99191183/165935845-7d530f47-b1f4-4f6b-9976-000a05774632.png)

![2](https://user-images.githubusercontent.com/99191183/165935443-11dfd944-eec0-4dd1-a191-d67bb26c6f81.png)

But I do n’t know if the model of the conversion is completed is these two. I temporarily think that it is these two models and then make the next step.
I set the variables in the detector.py file as follows.
![3](https://user-images.githubusercontent.com/99191183/165936006-d37076d8-bf22-4807-86d9-1582f6333e64.png)
![4](https://user-images.githubusercontent.com/99191183/165936014-9a393d0d-bb6b-449a-9232-3989badea514.png)

But in the end, this error appears。May I ask what is the reason？

![5](https://user-images.githubusercontent.com/99191183/165936088-41909b35-0cd1-4143-b477-023dbd701528.png)
As a beginner, my code reading ability is very weak, so I will always ask you the question. Thank you very much for your help.

**Comment by xin4431** [comment]
I have done model conversion via trt.py.
Is it the two files marked in the picture?

![1](https://user-images.githubusercontent.com/99191183/165951256-262343b2-5849-4182-9a4b-f6812989319f.png)

I assumed that it was these two files, and put them into detector.py and run, the error is as follows

![2](https://user-images.githubusercontent.com/99191183/165951269-abca47bd-b688-46da-89d0-53b7662dae6c.png)

![3](https://user-images.githubusercontent.com/99191183/165951282-bcbc2ef5-6507-4df8-9c54-2bc4b9a4e5e3.png)

![4](https://user-images.githubusercontent.com/99191183/165951294-f0bb34b8-6cc4-4e8a-8492-0435c786b517.png)

As a beginner, my coding skills are still weak. Sorry for the inconvenience caused by my question.
thanks a lot for your answer

**Comment by xin4431** [comment]
there is a problem---》       TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0


my cuda 11.1 cudnn8.2.1 pytorch1.11
How to solve this problem?

**Comment by xin4431** [comment]
![1](https://user-images.githubusercontent.com/99191183/166244790-1f53cddd-e34b-4214-91d9-0b0c90fe0c62.png)
Problems after running

**Comment by vanhaito** [comment]
Hope following old similar issue may help you in case you are facing: https://github.com/NVIDIA/TensorRT/issues/317
