### ISSUE TITLE
 YOLOX-ByteTrack-Car-Counter

### ISSUE THREAD

**Issue by ghost** [vanhaito/YOLOX-ByteTrack-Car-Counter#2]
https://github.com/vanhaito/YOLOX-ByteTrack-Car-Counter

i have two questions.

1. How to customize the range of drawing lines?
for example, i want to change the horizontal line to a straight line.

2. how to save the vedio?

thanks a lot.

**Comment by vanhaito** [comment]
Dear @stphtan94117 :
- Question 1: To draw a straight line you need to modify start point and end point in line 164 in detector.py:
  + start_point = (0.5 * width, 0)
  + end_point = (0.5 *width, height)
- Question 2: You could use cv2.VideoWriter() to save video.

**Comment by ghost** [comment]
hi sir
https://www.youtube.com/watch?v=HrPCdDUDBr4
this video can count every lane car , Light Painting(track) and detect km/h

so can your model modify those function?
