### ISSUE TITLE
Problem installing cython_bbox

### ISSUE THREAD

**Issue by litaldavar** [vanhaito/YOLOX-ByteTrack-Car-Counter#5]
Hi 
I have an error when installing cython_bbox

error: 
![image](https://github.com/vanhaito/YOLOX-ByteTrack-Car-Counter/assets/4908360/da995906-d06e-403b-8373-1c854b9ff128)
Please help

**Comment by vanhaito** [comment]
Sorry for my lately reponse. To solve your problem, just directly install from pypi:
https://pypi.org/project/Cython/
